#!/usr/bin/env bun

import { lstat, readFile, readdir, writeFile } from "node:fs/promises"
import { resolve } from "node:path"

const REPO_ROOT = resolve(import.meta.dir, "..")
const AGENTS_PATH = resolve(REPO_ROOT, "AGENTS.md")

export async function renderAgentsMd(): Promise<string> {
	const sources = [
		"CLAUDE.md",
		...(await readdir(resolve(REPO_ROOT, ".claude/rules")))
			.filter((name) => name.endsWith(".rule.md"))
			.sort()
			.map((name) => `.claude/rules/${name}`),
	]
	const sections = await Promise.all(sources.map(async (source) => {
		const content = (await readFile(resolve(REPO_ROOT, source), "utf8")).trimEnd()
		return `<!-- BEGIN SOURCE: ${source} -->\n\n${content}\n\n<!-- END SOURCE: ${source} -->`
	}))
	return [
		"# AGENTS.md",
		"",
		"> Generated by `bun scripts/sync-agents-md.ts` from `CLAUDE.md` and enabled `.claude/rules/*.rule.md` files.",
		"> Edit the source files, then regenerate this file; do not replace it with a symlink.",
		"",
		...sections,
		"",
	].join("\n")
}

export async function assertAgentsMdCurrent(): Promise<void> {
	const metadata = await lstat(AGENTS_PATH)
	if (metadata.isSymbolicLink()) throw new Error("AGENTS.md must be a regular generated file, not a symlink")
	const [actual, expected] = await Promise.all([readFile(AGENTS_PATH, "utf8"), renderAgentsMd()])
	if (actual !== expected) throw new Error("AGENTS.md is stale; run `bun scripts/sync-agents-md.ts`")
}

if (import.meta.main) {
	if (process.argv.includes("--check")) {
		await assertAgentsMdCurrent()
	} else {
		await writeFile(AGENTS_PATH, await renderAgentsMd())
	}
}
